blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='post_list'),
    path('view/<int:pk>/', PostDetailView.as_view(), name='post_view'),
    path('create/', never_cache(PostCreateView.as_view()), name='post_create'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='post_edit'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import HomePageView, MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, LogListView, active_toggle, \
    MessageListView, \
    MessageCreateView, ClientDetailView, MessageDetailView, MessageUpdateView, MessageDeleteView

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),

    path('list/', MailingListView.as_view(), name='mailing_list'),
    path('view/<int:pk>/', MailingDetailView.as_view(), name='mailing_view'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('edit/<int:pk>/', MailingUpdateView.as_view(), name='mailing_edit'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),

    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('<int:pk>/client_detail/', ClientDetailView.as_view(), name='client_detail'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_edit/<int:pk>/', ClientUpdateView.as_view(), name='client_edit'),
    path('client_confirm_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_confirm_delete'),

    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('<int:pk>/message_detail/', MessageDetailView.as_view(), name='message_detail'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_confirm_delete'),

    path('log_list/', LogListView.as_view(), name='log_list'),
    path('activity/<int:pk>/', active_toggle, name='activity')
]

mailing/models.py
from django.db import models
from django.db.models.functions import datetime
from config import settings

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    """Клиент для рассылки"""
    first_name = models.CharField(max_length=40, verbose_name='Имя')
    last_name = models.CharField(max_length=40, verbose_name='Фамилия')
    email = models.EmailField(unique=True, verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.first_name} {self.last_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('last_name', 'first_name')


class Message(models.Model):
    """Сообщение для рассылки"""
    title = models.CharField(max_length=100, verbose_name='Тема сообщения', default='Без темы')
    text = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('title',)


class Mailing(models.Model):
    """Информация о рассылки"""
    STATUS_CHOICES = [
        ('created', 'Создано'),
        ('started', 'Запущено'),
        ('completed', 'Завершено'),
    ]

    PERIOD_CHOICES = [
        ('once', '1 раз'),
        ('daily', 'Ежедневно'),
        ('weekly', 'Еженедельно'),
        ('monthly', 'Ежемесячно'),
    ]

    start_point = models.DateTimeField(verbose_name='Начать рассылку', default=datetime.datetime.now)
    stop_point = models.DateTimeField(verbose_name='Завершить рассылку', default=datetime.datetime.now)
    period = models.CharField(max_length=20, verbose_name='Периодичность', choices=PERIOD_CHOICES, default='once')
    status = models.CharField(max_length=20, verbose_name='Статус', choices=STATUS_CHOICES, default='created')

    client = models.ManyToManyField(Client, verbose_name='Клиенты')
    message = models.ForeignKey(Message, verbose_name='Сообщение', on_delete=models.CASCADE, **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, verbose_name='Владелец', **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активная')

    def __str__(self):
        return f'{self.start_point} {self.period} {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            ('set_is_active', 'Изменить период'),
        ]


class Log(models.Model):
    """Логи для рассылки"""
    LOG_CHOICES = [
        (True, 'Успешно'),
        (False, 'Ошибка')
    ]
    attempt_time = models.DateTimeField(verbose_name='Последняя попытка', **NULLABLE)
    attempt_status = models.CharField(max_length=10, verbose_name='Статус попытки', choices=LOG_CHOICES, default=True)
    server_response = models.TextField(verbose_name='Ответ сервера', **NULLABLE)

    mailing = models.ForeignKey(Mailing, verbose_name='Рассылка', on_delete=models.CASCADE, **NULLABLE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент рассылки', **NULLABLE)

    def __str__(self):
        return f'{self.attempt_time}, статус : {self.attempt_status}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailing/forms.py
from django import forms
from django.forms import DateTimeInput

from mailing.models import Client, Mailing, Message
from mailing.services import StileFormMixin


class ClientForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ['first_name', 'last_name', 'email', 'comment']
        #fields = '__all__'


class MailingForm(StileFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['client'].queryset = Client.objects.filter(owner=user)

    start_point = forms.DateTimeField(
        label='Время старта',
        required=False,
        widget=DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}, format='%Y-%m-%dT%H:%M')
    )

    stop_point = forms.DateTimeField(
        label='Время окончания',
        required=False,
        widget=DateTimeInput(attrs={'type': 'datetime-local', 'class': 'form-control'}, format='%Y-%m-%dT%H:%M')
    )

    class Meta:
        model = Mailing
        exclude = '__all__'


class MessageForm(StileFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

mailing/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import Http404
from django.shortcuts import get_object_or_404, redirect

from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView

from blog.models import Post
from mailing.forms import ClientForm, MailingForm, MessageForm
from mailing.models import Mailing, Client, Message, Log


class HomePageView(TemplateView):
    template_name = 'mailing/main_page.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['mailing_count'] = Mailing.objects.all().count()
        context_data['active_mailing_count'] = Mailing.objects.filter(is_active=True, ).count()
        context_data['clients_count'] = Client.objects.all().distinct().count()
        context_data['posts'] = Post.objects.all()[:3]

        return context_data


class MailingListView(LoginRequiredMixin, ListView):
    """Просмотр списка рассылок"""
    model = Mailing


class MailingDetailView(LoginRequiredMixin, DetailView):
    """Просмотр рассылки"""
    model = Mailing


class MailingCreateView(LoginRequiredMixin, CreateView):
    """Создание"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:home')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form, *args, **kwargs):
        if form.is_valid():
            new_mailing = form.save(commit=False)
            new_mailing.owner = self.request.user
            new_mailing.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mailing:mailing_list')


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if not self.request.user.is_superuser or self.object.owner != self.request.user:
            raise Http404
        return self.object


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление"""
    model = Mailing
    success_url = reverse_lazy('mailing:list')


class ClientListView(ListView):
    """Просмотр списка клиентов"""
    model = Client


class ClientCreateView(LoginRequiredMixin, CreateView):
    """Создание клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)



class ClientDetailView(LoginRequiredMixin, DetailView):
    """Детали клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_detail')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    """Редактирование клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    """Удаление клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_confirm_delete')


class MessageListView(LoginRequiredMixin, ListView):
    """Просмотр сообщений"""
    model = Message


class MessageDetailView(LoginRequiredMixin, DetailView):
    """Детальный просмотр сообщений"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_detail')


class MessageCreateView(LoginRequiredMixin, CreateView):
    """Создание клиента"""
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_list')


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mailing:message_edit')

    def get_success_url(self):
        return reverse('mailing:message_edit', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:message_list')

    # success_url = reverse_lazy('mailing:message_confirm_delete')

    # def get_success_url(self):
    #    return reverse('dogs:message_edit', args=[self.kwargs.get('pk')])


class LogListView(ListView):
    """Просмотр логов"""
    model = Log

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['all'] = context_data['object_list'].count()
        context_data['success'] = context_data['object_list'].filter(attempt_status=True).count()
        context_data['error'] = context_data['object_list'].filter(attempt_status=False).count()
        return context_data


@login_required
@permission_required('mailing.set_is_active')
def active_toggle(request, pk):
    mailing_item = get_object_or_404(Mailing, pk=pk)
    if mailing_item.is_active:
        mailing_item.is_active = False
    else:
        mailing_item.is_active = True
    mailing_item.save()
    return redirect(reverse('mailing:mailing_list'))

mailing/templates/mailing/base.html

{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">


    <!-- Bootstrap core CSS -->
    <!--link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


</head>
<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Информация</h4>
                    <p class="text-muted"></p>
                </div>
                {% include 'mailing/includes/inc_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Спамер</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ title }}</h1>
                <p class="lead text-muted">Рассылка сообщений</p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}


        </div>
    </div>

</main>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1"></p>
        <p class="mb-0"><a href="/"></a><a
                href="/docs/5.0/getting-started/introduction/"></a>.</p>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<script defer src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Удаление клиента
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить клиента {{ object.name }}</p>
                <button type="submit" class="btn btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-warning-outline" href=" {% url 'mailing:client_list' %}">Отмена</a>
            </div>
        </div>
    </div>
</form>


{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о клиенте
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Ф.И.</td>
                            <td>{{ object.first_name }} {{ object.last_name }}</td>
                        </tr>
                        <tr>
                            <td>Емаил</td>
                            <td>{{ object.email }}</td>
                        </tr>
                        <tr>
                            <td>Комментарий</td>
                            <td>{{ object.comment }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <input type="button" onclick="history.back();" value="Назад" style="margin-top: 10px;"/>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:client_create' %}">Добавить клиента</a>
</div>
{% for object in object_list %}
<div class="col-md-4">
    <div class="card md-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mailing:client_detail' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Показать</a>
                    <a href="{% url 'mailing:client_edit' object.pk %}"
                       type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                    <a href="{% url 'mailing:client_confirm_delete' object.pk %}"
                       type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/log_list.html
{%  extends 'mailing/base.html'%}

{% block content %}

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header"><h5 class="card-title">Информация о логах</h5></div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Общее количество</td>
                            <td>{{ all }}</td>
                        </tr>
                        <tr>
                            <td>Количество успешных</td>
                            <td>{{ success }}</td>
                        </tr>
                        <tr>
                            <td>Количество неудачных</td>
                            <td>{{ error }}</td>
                    </table>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
        </div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку "{{ object.title }}" ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:mailing_list' %}" class="btn btn-success">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{%  extends 'mailing/base.html'%}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    {{ object.client }}
                </div>
                <div class="card-body">
                    {{ object.message }}
                </div>
                <div class="card-footer">
                    {{ object.start_point }}, {{ object.stop_point }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12">
    <form class="row" method="post">
        <div class="card">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:mailing_create' %}">Добавить рассылку</a>
</div>
{% for object in object_list %}
    <div class="col-md-4">
        <div class="card md-4 box-shadow">
            <div class="card-body">
               <p class="card-text"> {{ object }}</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'mailing:mailing_view' object.pk %}"
                            class="btn btn-sm btn-outline-secondary">Показать</a>
                        <a href="{% url 'mailing:mailing_edit' object.pk %}"
                            type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                        <a href="{% url 'mailing:mailing_delete' object.pk %}"
                            type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/main_page.html
{%  extends 'mailing/base.html'%}

{% block content %}

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header"><h5 class="card-title">Информация о рассылках</h5></div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Количество рассылок всего</td>
                            <td>{{ mailing_count}}</td>
                        </tr>
                        <tr>
                            <td>Количество активных рассылок</td>
                            <td>{{ active_mailing_count }}</td>
                        </tr>
                        <tr>
                            <td>Количество уникальных клиентов для рассылок</td>
                            <td>{{ clients_count }}</td>
                        </tr>

                    </table>
                    <div class="card-footer"></div>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"><h5 class="card-title">Посты</h5></div>
                <div class="card-body">
                    {% for post in posts %}
                        {{ post.title }}
                    {% endfor %}
                </div>

                <div class="card-footer"></div>

            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить сообщение "{{ object.title }}" ?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'mailing:message_list' %}" class="btn btn-success">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Информация о сообщении
                    </h3>
                </div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td>Тема</td>
                            <td>{{ object.title }}</td>
                        </tr>
                        <tr>
                            <td>Сообщение</td>
                            <td>{{ object.text }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <input type="button" onclick="history.back();" value="Назад" style="margin-top: 10px;"/>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Новое сообщение
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

mailing/templates/mailing/message_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="col-12 mb-5">
    <a class="btn btn-outline-primary" href="{% url 'mailing:message_create' %}">Добавить сообщение</a>
</div>
{% for object in object_list %}
    <div class="col-md-4">
    <div class="card md-4 box-shadow">
        <div class="card-body">
            <p class="card-text">
                {{ object }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="{% url 'mailing:message_detail' object.pk %}"
                       class="btn btn-sm btn-outline-secondary">Показать</a>
                    <a href="{% url 'mailing:message_edit' object.pk %}"
                       type="button" class="btn btn-sm btn-outline-secondary">Изменить</a>
                    <a href="{% url 'mailing:message_confirm_delete' object.pk %}"
                       type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}